/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure_college_documents;
import awsfileoperation.FileDownload;
import awsfileoperation.FileUpload;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.BasicAWSCredentials;
import db_operations.Biggest_Document_ID;
import db_operations.DBDriver;
import db_operations.Datakeeper;
import db_operations.Document_Info_Inserter;
import db_operations.Email_ID_Fetcher;
import db_operations.Filename_Fetcher;
import db_operations.Terminal_Key_Fetcher;
import db_operations.Upload_Document_Info_Table_Creator;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author welcome
 */
public class Upload_Document_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Upload_Document_Frame
     */
    public static String filename="";
    public Upload_Document_Frame() {
        super("Upload Document Frame");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Upload Documents");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Select File");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/browse.jpg"))); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/upload.png"))); // NOI18N
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(520, 250, 940, 390);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure_college_documents/image 4.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 2000, 1000);

        jMenu1.setText("Manage Profile");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editstaff.png"))); // NOI18N
        jMenuItem1.setText("Edit Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Document");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/upload.png"))); // NOI18N
        jMenuItem2.setText("Upload Document");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jMenuItem3.setText("View History");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/download.png"))); // NOI18N
        jMenuItem5.setText("Download History");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logout");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JFileChooser js=new JFileChooser();
        js.showOpenDialog(js);
        File f=js.getSelectedFile();
       String  path1 = f.getAbsolutePath();
       filename=f.getName();
       jTextField1.setText(path1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Statement st=new DBDriver().createConnection();
        boolean flag=new Upload_Document_Info_Table_Creator().create_Upload_Document_Table_Creator(st);
        String filepath=jTextField1.getText();
        
         File f=new File(Datakeeper.path);
        if(!f.exists())
        {
            f.mkdirs();
        }
        File f1 = new File(filepath);
        System.out.println("File Size : "+f1.length());
        
        if(f1.length()>256000)
        {
            JOptionPane.showMessageDialog(null, "Size Limit Excceds");
        }
        else if(f1.length()<10000)
        {
            JOptionPane.showMessageDialog(null, "Size should in between 10 to 256 kb");
        }
        else
        {
            String bucketName = "mycollegedocumentbucket";
        AWSCredentials credentials = new BasicAWSCredentials();//add acess key and secret key here

            DateAndTime dt = new DateAndTime();
            String date = dt.getDate(); 
            String time = dt.getTime();
            String sdt = date + " , " + time;

            FileUpload fu = new FileUpload();
            FileDownload fd = new FileDownload();
            Document_Info_Inserter dii=new Document_Info_Inserter();

            int sid=new Serial_Number().GetSId();
            int sdid=sid+1;
            String serial_id=Integer.toString(sdid);


            if(sid==0)
            {
                String text= new FileByteReader().readContentIntoByteArray(new File(filepath));
                String hash=new MD5Hash().MDfive(text);
                if(dii.isDocument_Info_inserted(st, serial_id, Login_Frame.username, filename, sdt, hash))
                {
                    if(fu.awsFileUpload(credentials, bucketName, filepath))
                        JOptionPane.showMessageDialog(null, "Document Uploaded Successfully");

                }
                else
                    JOptionPane.showMessageDialog(null, "Error In Document Upload");
            }
            else
            {  
                ArrayList filenames_id=new Filename_Fetcher().getFilename(st);
                String current_hash="";

                String bigdoc=new Biggest_Document_ID().getBigDocid();
                String Last_terminal_key=new Terminal_Key_Fetcher().getTerminalKey(st, bigdoc);
                System.out.println("last terminal key is: "+Last_terminal_key);

                for (int i = 0; i < filenames_id.size(); i++)
                {
                    ArrayList row=(ArrayList)filenames_id.get(i);
                    String current_file=(String)row.get(1);
                    System.out.println("Cuurent File: "+current_file);

                    if(i==0)
                    {
                        try
                        {
                            boolean flag1=new FileDownload().awsFileDownload(credentials, bucketName, current_file);
                            if(flag1==true)
                            {
                                String current_text= new FileByteReader().readContentIntoByteArray(new File(Datakeeper.path+"//"+current_file));
                                current_hash=new MD5Hash().MDfive(current_text);
                                System.out.println("Current hash:"+current_hash);
                            }
                        }
                        catch(Exception ex)
                        {
                            System.out.println("Exception is: "+ex);
                        }
                    }
                    else
                    {
                        try 
                        {
                            boolean flag1 = new FileDownload().awsFileDownload(credentials, bucketName, current_file);
                            if(flag1==true)
                            {
                                String newtext= new FileByteReader().readContentIntoByteArray(new File(Datakeeper.path+"//"+current_file));
                                String newhash_generator=newtext+current_hash;
                                current_hash=new MD5Hash().MDfive(newhash_generator);
                                System.out.println("new hash is: "+current_hash);
                            }
                        } 
                        catch (IOException ex) 
                        {
                            Logger.getLogger(Upload_Document_Frame.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
                if(Last_terminal_key.equals(current_hash))
                    {
                        System.out.println("Matched");
                        String text= new FileByteReader().readContentIntoByteArray(new File(filepath));
                        String newupload=text+current_hash;
                        String newhashkey=new MD5Hash().MDfive(newupload);

                         if(dii.isDocument_Info_inserted(st, serial_id, Login_Frame.username, filename, sdt, newhashkey))
                        {
                            if(fu.awsFileUpload(credentials, bucketName, filepath))
                                JOptionPane.showMessageDialog(null, "Document Uploaded Successfully");

                        }
                    }
                    else
                    {
                        System.out.println("Not Matched");
                        String subject="Regarding College Document Cloud Integrity Violation";
                         JOptionPane.showMessageDialog(null, "The cloud is not safe to upload the document \n The integrity is violated , so we can not upload the document");
                        ArrayList email=new Email_ID_Fetcher().getEmailID(st);
                        for (int i = 0; i < email.size(); i++)
                        {
                             String body="Dear "+Login_Frame.username+ "\n The College Document Cloud Storage integrity is violated. Hence, Cloud Storage is not safe.So, Please contact Admin immediately. \n\n\n Thank You,\n Securing College Document System";
                            String email_id=(String)email.get(i);
                            new SendMail().send(body, subject, email_id);
                        }

                }    
            }
        }
        
        
       // System.out.println("Hash key "+hash);
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Edit_Profile_Frame epf=new Edit_Profile_Frame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        epf.setVisible(true);
        epf.setSize(d);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Upload_Document_Frame udf=new Upload_Document_Frame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        udf.setVisible(true);
        udf.setSize(d);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        View_Uploaded_History_Frame vuhf=new View_Uploaded_History_Frame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        vuhf.setVisible(true);
        vuhf.setSize(d);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Download_File_Frame dff=new Download_File_Frame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        dff.setVisible(true);
        dff.setSize(d);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       // TODO add your handling code here:
        this.dispose();
        Login_Frame dff=new Login_Frame();
       Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
       dff.setVisible(true);
       dff.setSize(d);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upload_Document_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upload_Document_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upload_Document_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upload_Document_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upload_Document_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
